/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/catalog/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feed */
        get: operations["get_feed_api_v1_catalog_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_v1_catalog_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commerce/cart/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_v1_commerce_cart_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commerce/operations/by-idempotency/{idempotency_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get By Idempotency Key */
        get: operations["get_by_idempotency_key_api_v1_commerce_operations_by_idempotency__idempotency_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commerce/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Operation */
        get: operations["get_operation_api_v1_commerce_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commerce/operations/{operation_id}/accept-facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Facts */
        post: operations["accept_facts_api_v1_commerce_operations__operation_id__accept_facts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commerce/operations/{operation_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Item */
        post: operations["add_item_api_v1_commerce_operations__operation_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guide/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_guide_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guide/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_guide_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guide/sessions/{session_id}/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add */
        post: operations["add_api_v1_guide_sessions__session_id__cart_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guide/sessions/{session_id}/cart/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_v1_guide_sessions__session_id__cart_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guide/sessions/{session_id}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare */
        post: operations["compare_api_v1_guide_sessions__session_id__compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guide/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Message */
        post: operations["post_message_api_v1_guide_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddCartItemRequest */
        AddCartItemRequest: {
            /** Confirmation Token */
            confirmation_token: string;
        };
        /** CartItemResponse */
        CartItemResponse: {
            /** Cart Id */
            cart_id: string;
            /** Cart Item Id */
            cart_item_id: string;
            /** Quantity */
            quantity: number;
            /** Session Id */
            session_id: string;
            /**
             * Simulated
             * @constant
             */
            simulated: true;
            /** Sku Id */
            sku_id: string;
            state: components["schemas"]["WorkflowState"];
            /** Unit Price Usd */
            unit_price_usd: number;
        };
        /** CartPreviewRequest */
        CartPreviewRequest: {
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /** Sku Id */
            sku_id: string;
        };
        /** CartPreviewResponse */
        CartPreviewResponse: {
            /** Confirmation Token */
            confirmation_token: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Inventory Units */
            inventory_units: number;
            /** Quantity */
            quantity: number;
            /** Session Id */
            session_id: string;
            /**
             * Simulated
             * @constant
             */
            simulated: true;
            /** Sku Id */
            sku_id: string;
            state: components["schemas"]["WorkflowState"];
            /** Subtotal Usd */
            subtotal_usd: number;
            /** Unit Price Usd */
            unit_price_usd: number;
        };
        /** CatalogEngagementResponse */
        CatalogEngagementResponse: {
            /** Comments */
            comments: number;
            /** Favorites */
            favorites: number;
            /** Likes */
            likes: number;
            /** Shares */
            shares: number;
        };
        /** CatalogFeedItemResponse */
        CatalogFeedItemResponse: {
            anchor_product: components["schemas"]["CatalogProductSummary"] | null;
            /** Anchor Product Id */
            anchor_product_id: string | null;
            /** Caption Zh */
            caption_zh: string;
            /**
             * Commerce Status
             * @enum {string}
             */
            commerce_status: "none" | "available" | "unavailable";
            /** Content Context Id */
            content_context_id: string | null;
            /** Creator Display Name */
            creator_display_name: string;
            /** Creator Handle */
            creator_handle: string;
            engagement: components["schemas"]["CatalogEngagementResponse"];
            /** Id */
            id: string;
            media: components["schemas"]["CatalogMediaResponse"];
            /**
             * Synthetic
             * @constant
             */
            synthetic: true;
        };
        /** CatalogFreshnessResponse */
        CatalogFreshnessResponse: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Facts Version */
            facts_version: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** CatalogMediaResponse */
        CatalogMediaResponse: {
            /** Alt Zh */
            alt_zh: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "video" | "image";
            /** License Ref */
            license_ref: string;
            /** Poster Src */
            poster_src: string | null;
            /** Src */
            src: string;
        };
        /** CatalogProductResponse */
        CatalogProductResponse: {
            /**
             * Active Filter Type
             * @enum {string}
             */
            active_filter_type: "mineral" | "organic" | "hybrid";
            /** Brand */
            brand: string;
            /** Broad Spectrum */
            broad_spectrum: boolean;
            /** Description Zh */
            description_zh: string;
            /** Display Name Zh */
            display_name_zh: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Facts Version */
            facts_version: string;
            /**
             * Finish
             * @enum {string}
             */
            finish: "dewy" | "natural" | "matte";
            /** Fragrance Free */
            fragrance_free: boolean;
            /** Id */
            id: string;
            /** Ingredient Highlights */
            ingredient_highlights: string[];
            /** List Price Usd */
            list_price_usd: number;
            media: components["schemas"]["CatalogMediaResponse"];
            /** Name */
            name: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Promotion */
            promotion: string | null;
            shipping: components["schemas"]["CatalogShippingResponse"];
            /** Skin Types */
            skin_types: ("dry" | "combination" | "oily" | "sensitive")[];
            /** Skus */
            skus: components["schemas"]["CatalogSkuResponse"][];
            /** Spf */
            spf: number;
            /** Store Name */
            store_name: string;
            /**
             * Synthetic
             * @constant
             */
            synthetic: true;
            /** Water Resistance Minutes */
            water_resistance_minutes: (40 | 80) | null;
            /**
             * White Cast Risk
             * @enum {string}
             */
            white_cast_risk: "low" | "medium" | "high";
        };
        /** CatalogProductSummary */
        CatalogProductSummary: {
            /** Brand */
            brand: string;
            /** Display Name Zh */
            display_name_zh: string;
            /** Id */
            id: string;
            /** Image Src */
            image_src: string;
            /** Name */
            name: string;
            /** Starting Price Usd */
            starting_price_usd: number;
        };
        /** CatalogShippingResponse */
        CatalogShippingResponse: {
            /** Eta Max Days */
            eta_max_days: number;
            /** Eta Min Days */
            eta_min_days: number;
            /** Fee Usd */
            fee_usd: number;
            /**
             * Market
             * @constant
             */
            market: "US";
            /** Return Summary Zh */
            return_summary_zh: string;
        };
        /** CatalogSkuResponse */
        CatalogSkuResponse: {
            /** Id */
            id: string;
            /** Image Src */
            image_src: string;
            /** In Stock */
            in_stock: boolean;
            /** Inventory Units */
            inventory_units: number;
            /** Label */
            label: string;
            /** Price Usd */
            price_usd: number;
            /** Size Ml */
            size_ml: number;
        };
        /** ClaimVerification */
        ClaimVerification: {
            /** Claim Id */
            claim_id: string;
            /** Evidence Id */
            evidence_id: string;
            status: components["schemas"]["EvidenceStatus"];
            /** Text */
            text: string;
        };
        /** CommerceAcceptFactsRequest */
        CommerceAcceptFactsRequest: {
            /** Expected Transaction Revision */
            expected_transaction_revision: number;
        };
        /**
         * CommerceAction
         * @enum {string}
         */
        CommerceAction: "SELECT_SKU" | "SET_QUANTITY" | "PREVIEW_CART" | "ACCEPT_UPDATED_FACTS" | "CONFIRM_ADD_TO_CART" | "CANCEL_CONFIRMATION" | "RESELECT_SKU" | "RETRY_COMMERCE_OPERATION" | "RECONCILE_COMMIT" | "RETURN_TO_PRODUCT" | "CONTINUE_BROWSING";
        /** CommerceAddRequest */
        CommerceAddRequest: {
            /** Confirmation Token */
            confirmation_token: string;
            /**
             * Demo Scenario
             * @default NORMAL
             * @enum {string}
             */
            demo_scenario: "NORMAL" | "COMMIT_STATUS_UNKNOWN";
            /** Expected Transaction Revision */
            expected_transaction_revision: number;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** CommerceFactDiff */
        CommerceFactDiff: {
            /** Current Value */
            current_value: string | number | boolean | null;
            /** Field */
            field: string;
            /** Previous Value */
            previous_value: string | number | boolean | null;
        };
        /** CommerceFactsResponse */
        CommerceFactsResponse: {
            /** Facts Version */
            facts_version: string;
            /** In Stock */
            in_stock: boolean;
            /** Inventory Units */
            inventory_units: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Product Id */
            product_id: string;
            /** Quantity */
            quantity: number;
            /** Sku Id */
            sku_id: string;
            /** Subtotal Usd */
            subtotal_usd: number;
            /** Unit Price Usd */
            unit_price_usd: number;
        };
        /** CommerceOperationResponse */
        CommerceOperationResponse: {
            /** Allowed Actions */
            allowed_actions: components["schemas"]["CommerceAction"][];
            commerce_view_kind: components["schemas"]["CommerceStep"];
            /** Confirmation Expires At */
            confirmation_expires_at?: string | null;
            /** Confirmation Token */
            confirmation_token?: string | null;
            /** Error Code */
            error_code?: string | null;
            facts: components["schemas"]["CommerceFactsResponse"];
            /** Facts Diff */
            facts_diff?: components["schemas"]["CommerceFactDiff"][];
            /** Facts Version */
            facts_version: string;
            /** Guide Session Id */
            guide_session_id?: string | null;
            /** Operation Id */
            operation_id: string;
            operation_status: components["schemas"]["CommerceOperationStatus"];
            /** Product Id */
            product_id: string;
            /**
             * Purchase Origin
             * @enum {string}
             */
            purchase_origin: "FEED" | "AI";
            /** Quantity */
            quantity: number;
            receipt?: components["schemas"]["CommerceReceiptResponse"] | null;
            /**
             * Simulated
             * @constant
             */
            simulated: true;
            /** Sku Id */
            sku_id: string;
            /** Source Guide Revision */
            source_guide_revision?: number | null;
            /** Transaction Revision */
            transaction_revision: number;
        };
        /**
         * CommerceOperationStatus
         * @enum {string}
         */
        CommerceOperationStatus: "ACTIVE" | "RECONCILIATION_REQUIRED" | "SUCCEEDED" | "FAILED" | "CANCELLED";
        /** CommercePreviewRequest */
        CommercePreviewRequest: {
            /**
             * Demo Scenario
             * @default NORMAL
             * @enum {string}
             */
            demo_scenario: "NORMAL" | "PRICE_CHANGED" | "OUT_OF_STOCK";
            /**
             * Expected Transaction Revision
             * @default 0
             */
            expected_transaction_revision: number;
            /** Guide Session Id */
            guide_session_id?: string | null;
            /** Previous Operation Id */
            previous_operation_id?: string | null;
            /** Product Id */
            product_id: string;
            /**
             * Purchase Origin
             * @enum {string}
             */
            purchase_origin: "FEED" | "AI";
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /** Sku Id */
            sku_id: string;
            /** Source Guide Revision */
            source_guide_revision?: number | null;
        };
        /** CommerceReceiptResponse */
        CommerceReceiptResponse: {
            /** Cart Id */
            cart_id: string;
            /** Cart Item Id */
            cart_item_id: string;
            /**
             * Committed At
             * Format: date-time
             */
            committed_at: string;
            /** Facts Version */
            facts_version: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Operation Id */
            operation_id: string;
            /**
             * Order Created
             * @constant
             */
            order_created: false;
            /**
             * Payment Created
             * @constant
             */
            payment_created: false;
            /** Product Id */
            product_id: string;
            /** Quantity */
            quantity: number;
            /** Receipt Id */
            receipt_id: string;
            /**
             * Simulated
             * @constant
             */
            simulated: true;
            /** Sku Id */
            sku_id: string;
            /** Subtotal Usd */
            subtotal_usd: number;
            /** Unit Price Usd */
            unit_price_usd: number;
        };
        /**
         * CommerceStep
         * @enum {string}
         */
        CommerceStep: "PDP_READY" | "CHECKING_FACTS" | "AWAITING_CONFIRMATION" | "FACTS_CHANGED" | "COMMITTING" | "COMMIT_STATUS_UNKNOWN" | "SUCCEEDED" | "FAILED" | "CANCELLED";
        /** CompareRequest */
        CompareRequest: {
            /** Expected Conversation Revision */
            expected_conversation_revision?: number | null;
            /** Product Ids */
            product_ids: string[];
            /** Request Id */
            request_id?: string | null;
        };
        /** CompareResponse */
        CompareResponse: {
            /** Product Ids */
            product_ids: string[];
            rows: components["schemas"]["ComparisonRows"];
            /** Session Id */
            session_id: string;
            /**
             * Simulated
             * @constant
             */
            simulated: true;
            /**
             * State
             * @constant
             */
            state: "COMPARE";
        };
        /** ComparisonRows */
        ComparisonRows: {
            /** Finish */
            finish: ("dewy" | "natural" | "matte")[];
            /** Fragrance Free */
            fragrance_free: boolean[];
            /** Starting Price Usd */
            starting_price_usd: number[];
            /** Water Resistance Minutes */
            water_resistance_minutes: ((40 | 80) | null)[];
            /** White Cast Risk */
            white_cast_risk: ("low" | "medium" | "high")[];
        };
        /** ContentContextSummary */
        ContentContextSummary: {
            /** Anchor Product Id */
            anchor_product_id: string;
            /** Anchor Product Name */
            anchor_product_name: string;
            /** Caption */
            caption: string;
            /** Claims */
            claims: components["schemas"]["ClaimVerification"][];
            /** Creator Handle */
            creator_handle: string;
            /** Id */
            id: string;
        };
        /** CreateGuideSessionRequest */
        CreateGuideSessionRequest: {
            content_context_id: string;
            /** @constant */
            entry_point: "content";
            /**
             * @default en-US
             * @enum {string}
             */
            locale: "en-US" | "zh-CN";
        } | {
            /** @constant */
            entry_point: "search";
            /**
             * @default en-US
             * @enum {string}
             */
            locale: "en-US" | "zh-CN";
            search_query: string;
        };
        /**
         * EntryPoint
         * @enum {string}
         */
        EntryPoint: "content" | "search";
        /** EvidenceReference */
        EvidenceReference: {
            /** Evidence Id */
            evidence_id: string;
            /**
             * Source Kind
             * @enum {string}
             */
            source_kind: "public_rule" | "synthetic_review_aggregate";
            status: components["schemas"]["EvidenceStatus"];
            /** Summary */
            summary: string;
            /** Synthetic */
            synthetic: boolean;
            /** Title */
            title: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /**
         * EvidenceStatus
         * @enum {string}
         */
        EvidenceStatus: "SUPPORTED" | "CONFLICTING" | "INSUFFICIENT_EVIDENCE" | "SUBJECTIVE_MIXED";
        /** FeedResponse */
        FeedResponse: {
            /** Bottom Nav Variant */
            bottom_nav_variant: string;
            /** Feed Tabs */
            feed_tabs: string[];
            /** Items */
            items: components["schemas"]["CatalogFeedItemResponse"][];
        };
        /**
         * GuideAction
         * @enum {string}
         */
        GuideAction: "SEND_MESSAGE" | "CONFIRM_CONTEXT" | "ANSWER_CLARIFICATION" | "SKIP_CLARIFICATION" | "UPDATE_CONSTRAINTS" | "RELAX_CONSTRAINT" | "CONTINUE_WITH_KNOWN" | "REQUEST_COMPARISON" | "OPEN_PRODUCT" | "RETRY_GUIDE_OPERATION" | "RETURN_TO_FEED";
        /** GuideMessageRequest */
        GuideMessageRequest: {
            /** Expected Conversation Revision */
            expected_conversation_revision?: number | null;
            /** Message Id */
            message_id: string;
            /** Text */
            text: string;
        };
        /**
         * GuideStatus
         * @enum {string}
         */
        GuideStatus: "ACTIVE" | "WAITING_USER" | "SAFE_EXIT" | "FAILED";
        /**
         * GuideTranscriptKind
         * @enum {string}
         */
        GuideTranscriptKind: "OPENING" | "USER_TEXT" | "QUESTION" | "ANSWER" | "RECOMMENDATION" | "COMPARISON" | "NO_MATCH" | "SAFETY" | "RECOVERY";
        /** GuideTranscriptMessage */
        GuideTranscriptMessage: {
            comparison?: components["schemas"]["CompareResponse"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceReference"][];
            /** Id */
            id: string;
            kind: components["schemas"]["GuideTranscriptKind"];
            /** Quick Replies */
            quick_replies?: string[];
            /** Recommendations */
            recommendations?: components["schemas"]["RecommendationCard"][];
            /**
             * Redacted
             * @default false
             */
            redacted: boolean;
            role: components["schemas"]["GuideTranscriptRole"];
            /** Sequence */
            sequence: number;
            /** Text */
            text: string;
            verdict?: components["schemas"]["Verdict"] | null;
        };
        /**
         * GuideTranscriptRole
         * @enum {string}
         */
        GuideTranscriptRole: "USER" | "ASSISTANT";
        /** GuideTurnResponse */
        GuideTurnResponse: {
            /** Allowed Actions */
            allowed_actions: components["schemas"]["GuideAction"][];
            comparison?: components["schemas"]["CompareResponse"] | null;
            context: components["schemas"]["ContentContextSummary"];
            /**
             * Conversation Revision
             * @default 1
             */
            conversation_revision: number;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceReference"][];
            /**
             * Facts Snapshot At
             * Format: date-time
             */
            facts_snapshot_at: string;
            /** Guide Revision */
            guide_revision: number;
            guide_status: components["schemas"]["GuideStatus"];
            guide_view_kind: components["schemas"]["GuideViewKind"];
            /**
             * Kind
             * @enum {string}
             */
            kind: "opening" | "clarification" | "answer" | "recommendation" | "no_match" | "safety_boundary";
            /**
             * Locale
             * @enum {string}
             */
            locale: "en-US" | "zh-CN";
            /** Quick Replies */
            quick_replies?: string[];
            /** Recommendations */
            recommendations?: components["schemas"]["RecommendationCard"][];
            /** Session Id */
            session_id: string;
            state: components["schemas"]["WorkflowState"];
            /** Text */
            text: string;
            /** Trace Id */
            trace_id: string;
            /** Transcript */
            transcript?: components["schemas"]["GuideTranscriptMessage"][];
            verdict?: components["schemas"]["Verdict"] | null;
        };
        /**
         * GuideViewKind
         * @enum {string}
         */
        GuideViewKind: "OPENING_CONTEXT" | "ANSWER_READY" | "CONTEXT_CONFIRMATION" | "WAITING_CLARIFICATION" | "VERIFYING_FACTS" | "DECISION_READY" | "NO_MATCH" | "INSUFFICIENT_EVIDENCE" | "COMPARISON_READY" | "SAFE_BOUNDARY" | "RECOVERY_REQUIRED" | "FATAL_ERROR";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProductDetailResponse */
        ProductDetailResponse: {
            freshness: components["schemas"]["CatalogFreshnessResponse"];
            product: components["schemas"]["CatalogProductResponse"];
            /** Starting Price Usd */
            starting_price_usd: number;
            /**
             * Synthetic Disclosure
             * @constant
             */
            synthetic_disclosure: true;
        };
        /** RecommendationCard */
        RecommendationCard: {
            /** Brand */
            brand: string;
            /** Eligible Sku Ids */
            eligible_sku_ids: string[];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Fit Reasons */
            fit_reasons: string[];
            /** Name */
            name: string;
            /** Product Id */
            product_id: string;
            /** Starting Price Usd */
            starting_price_usd: number;
            /** Tradeoffs */
            tradeoffs: string[];
            verdict: components["schemas"]["Verdict"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "SUITABLE" | "CONDITIONAL" | "NOT_RECOMMENDED" | "INSUFFICIENT_EVIDENCE";
        /**
         * WorkflowState
         * @enum {string}
         */
        WorkflowState: "ENTRY_INGEST" | "UNDERSTAND" | "CLARIFY" | "VERIFY_CURRENT_PRODUCT" | "FILTER_AND_RETRIEVE" | "PRESENT_RECOMMENDATION" | "COMPARE" | "SKU_AND_CART_CONFIRM" | "FEEDBACK_AND_MEMORY";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_feed_api_v1_catalog_feed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
        };
    };
    get_product_api_v1_catalog_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_v1_commerce_cart_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommercePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommerceOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_by_idempotency_key_api_v1_commerce_operations_by_idempotency__idempotency_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idempotency_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommerceOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_operation_api_v1_commerce_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommerceOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_facts_api_v1_commerce_operations__operation_id__accept_facts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommerceAcceptFactsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommerceOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_item_api_v1_commerce_operations__operation_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommerceAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommerceOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_guide_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGuideSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuideTurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_guide_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuideTurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_api_v1_guide_sessions__session_id__cart_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCartItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_v1_guide_sessions__session_id__cart_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_guide_sessions__session_id__compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_api_v1_guide_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuideMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuideTurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
